linters:
  enable:
    - errcheck
    - govet
    - staticcheck

linters-settings:
  govet:
    enable-all: true
  staticcheck:
    checks: ["all"]

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
